[package]
name = "kidding"
version = "1.0.1"
authors = ["Canop <cano.petrole@gmail.com>"]
edition = "2018"
keywords = ["learn"]
license = "MIT"
categories = ["command-line-utilities"]
description = "an easy to tune program asking Math questions"

[dependencies]
crossterm = "0.16"
rand = "0.7"
